services:

  hello-world:
    build: .
    image: my-application:latest
    ports:
    - 3000:8000

  hello-budi:
    build: .
    image: my-application:latest
    ports:
    - 3001:8000
    environment:
    - USER_NAME=budi
  
  nginx:
    image: nginx:latest
    hostname: my-nginx
    container_name: my-nginx
    ports:
    - 3002:80 
    volumes:
    - ./static-content:/usr/share/nginx/html 
